name: codenic_bloc_use_case
description: A suite of abstract cubits to reduce boilerplate code and construct app use cases.
version: 0.1.0
repository: https://github.com/CodenicCoders/codenic_bloc_use_case
issue_tracker: https://github.com/CodenicCoders/codenic_bloc_use_case/issues
homepage: https://github.com/CodenicCoders/codenic_bloc_use_case
documentation: https://github.com/CodenicCoders/codenic_bloc_use_case

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.3  
  meta: ^1.8.0

dev_dependencies:
  bloc_test: ^9.0.3

  build_runner: ^2.1.11
  test: ^1.21.3
  very_good_analysis: ^3.0.1
