name: codenic_bloc_use_case
description: A suite of abstract cubits to reduce boilerplate code and construct app use cases.
version: 2.1.0+1
repository: https://github.com/CodenicCoders/codenic_bloc_use_case
issue_tracker: https://github.com/CodenicCoders/codenic_bloc_use_case/issues
homepage: https://github.com/CodenicCoders/codenic_bloc_use_case
documentation: https://github.com/CodenicCoders/codenic_bloc_use_case

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  fpdart: ^0.3.0

  meta: ^1.8.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.2
  test: ^1.22.0
  very_good_analysis: ^3.1.0
